title: The Inside View # name of the site
author: MichaÃ«l Trazzi # name of site's author
email: michael.trazzi@gmail.com # email of site's author
url: https://theinsideview.co # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  About AI progress.

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

favicon: "logo.jpeg"

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
